packages:
  - packages/shared
  - packages/engine
  - packages/workers
  - packages/ui
  - apps/*

auto-install-peers: true

ignoredBuiltDependencies:
  - better-sqlite3
  - electron
  - esbuild

prefer-workspace-packages: true

shared-workspace-lockfile: true

strict-peer-dependencies: false
