[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cleancue-workers"
version = "0.1.0"
description = "Audio analysis workers for CleanCue"
authors = [
    {name = "CommndrCody", email = "your-email@example.com"}
]
license = {text = "MIT"}
requires-python = ">=3.8"
dependencies = [
    "librosa>=0.10.1",
    "numpy>=1.24.0",
    "scipy>=1.10.0",
    "numba>=0.57.0",
    "soundfile>=0.12.1"
]

[project.optional-dependencies]
advanced = [
    "essentia-tensorflow>=2.1b6.dev1110",
    "aubio>=0.4.9"
]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=22.0.0",
    "flake8>=4.0.0"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 100
target-version = ['py38']

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
